#!/bin/bash

# objverify.sh
# Written by Daniel Kolkena, based on Kollin Prince's code
# Verifies object size on each disk.
# There must be at least 9 replicas to be able to restore. 
# If there are less than 9, the object is corrupted.
# Must be run in the ObjectForensic_* directory generated by ObjectForensic.pl!

while IFS="," read -r -a values; # Main loop, will iterate through list of objects in NeedsRecovery
do
	tid=$values[0];
	oid=$values[1];

	# read -p "Enter Tenant ID: " tid;
	# read -p "Enter Object ID: " oid; 

	for (( x=1; x<=12; x++)); # Checking all replications for a particular object
	do 
		host=$(mauiobjbrowser -t $tid -i $oid | grep -A 10 "Column #$(($x)):"| head -11 | grep SS: | awk -F ' ' '{print $2}'); 
		path=$(mauiobjbrowser -t $tid -i $oid | grep -A 10 "Column #$(($x)):"| head -11 | grep Path | awk -F ' ' '{print $2}');
		echo $host; ssh $host du $path;
	done
done < NeedsRecovery

